version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .data:/root/.data

  frontend:
    container_name: mazon
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - .data:/root/.data
#    volumes:
#      - './frontend:/app'
#      - ./frontend/app/node_modules
    ports:
      - '1337:80' # http://localhost:1337/
    depends_on:
      - backend
