spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:mem:mazon-db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

jwt:
  secret: ${MAZON_SECRET_KEY:x7D*6]]s#j4ZI{M"V"4+[X%KbTW+Y3GI^KJb+E!n8^<nRbCboV'68m<{H+nGYXJ}

debug: false

#spring.jpa.show-sql=true
